// Generated by openclaw-jev-trigger. Edit freely.
// Condition (plain language), judged by the agent's decisionModel via jev_when.
const WHEN = "The product's price went down compared with the previous observation";
const NOT_WHEN = "The price is the same or higher, or only the wording, layout, stock, or shipping changed";
const s = trigger.state ?? {};
const asText = (v) =>
  typeof v === "string" ? v
  : v && typeof v.aggregated === "string" ? v.aggregated
  : v && typeof v.text === "string" ? v.text
  : v && typeof v.content === "string" ? v.content
  : JSON.stringify(v);

const obs = asText(await web_fetch({ url: "https://shop.example/products/trail-runner-5" })).trim();
const v = await jev_when({ when: WHEN, notWhen: NOT_WHEN, evidence: obs, previous: s.last ?? null });

if (v.unavailable) {
  // Not a "no": the judge could not answer. Stay quiet, but do not go silent forever.
  const misses = (s.misses ?? 0) + 1;
  json({
    fire: misses === 3,
    message: `jev-trigger: the judge was unavailable ${misses} times in a row (${v.unavailable}). "${WHEN}" is not being checked.`,
    state: { ...s, misses },
  });
} else {
  const fire = v.matched;
  json({
    fire,
    message: `Condition met: ${WHEN}\n(p=${v.probability} ≥ ${v.threshold}, ${v.model})\n\nObservation:\n${obs.slice(-1500)}`,
    state: { last: obs.slice(-6000), matched: v.matched, p: v.probability, misses: 0 },
  });
}
