// Generated by openclaw-jev-trigger. Edit freely.
// Condition (plain language), judged by the agent's decisionModel via jev_when.
const WHEN = "The work in this thread is finished and the assistant has delivered its final result";
const NOT_WHEN = "The assistant is only paused: waiting for a reply, an approval, a CI run, or a background job, or it is still working";
const s = trigger.state ?? {};
const asText = (v) =>
  typeof v === "string" ? v
  : v && typeof v.aggregated === "string" ? v.aggregated
  : v && typeof v.text === "string" ? v.text
  : v && typeof v.content === "string" ? v.content
  : JSON.stringify(v);

const obs = asText(await exec({ command: "tail -n 4 ./thread.log" })).trim();
const v = await jev_when({ when: WHEN, notWhen: NOT_WHEN, evidence: obs });

if (v.unavailable) {
  // Not a "no": the judge could not answer. Stay quiet, but do not go silent forever.
  const misses = (s.misses ?? 0) + 1;
  json({
    fire: misses === 3,
    message: `jev-trigger: the judge was unavailable ${misses} times in a row (${v.unavailable}). "${WHEN}" is not being checked.`,
    state: { ...s, misses },
  });
} else {
  const fire = v.matched && !s.matched;
  json({
    fire,
    message: `Condition met: ${WHEN}\n(p=${v.probability} ≥ ${v.threshold}, ${v.model})\n\nObservation:\n${obs.slice(-1500)}`,
    state: { matched: v.matched, p: v.probability, misses: 0 },
  });
}
