// Generates an OpenClaw automation trigger script (`--trigger-script`) that
// observes something, asks `jev_when`, and returns { fire, message, state }.
// The script runs in the headless Code Mode executor: every enabled tool is an
// async global, `trigger.state` is last run's state, `json()` returns the result.

export type Source =
  | { kind: "exec"; command: string }
  | { kind: "fetch"; url: string }
  | { kind: "tool"; name: string; args: Record<string, unknown> };

export type ScriptOptions = {
  when: string;
  notWhen?: string;
  source: Source;
  /** Pass last run's observation so change conditions work ("price dropped"). */
  compare?: boolean;
  /** Fire on every matching run instead of only on the false -> true edge. */
  level?: boolean;
  threshold?: number;
  keep?: "head" | "tail";
  /** Fire one alert after this many unavailable judgements in a row (0 = never). */
  alertAfter?: number;
  /** Characters of observation kept in state and in the fired message. */
  stateChars?: number;
};

const IDENT = /^[A-Za-z_$][\w$]*$/;

export function renderScript(o: ScriptOptions): string {
  if (!o.when.trim()) throw new Error("--when is required");
  const alertAfter = o.alertAfter ?? 3;
  const stateChars = o.stateChars ?? 6000;
  const q = (v: unknown) => JSON.stringify(v);

  let observe: string;
  switch (o.source.kind) {
    case "exec":
      observe = `await exec({ command: ${q(o.source.command)} })`;
      break;
    case "fetch":
      observe = `await web_fetch({ url: ${q(o.source.url)} })`;
      break;
    case "tool":
      if (!IDENT.test(o.source.name)) throw new Error(`not a callable tool name: ${o.source.name}`);
      observe = `await ${o.source.name}(${q(o.source.args)})`;
      break;
  }

  const askLines = [
    "when: WHEN",
    ...(o.notWhen?.trim() ? ["notWhen: NOT_WHEN"] : []),
    "evidence: obs",
    ...(o.compare ? ["previous: s.last ?? null"] : []),
    ...(o.threshold !== undefined ? [`threshold: ${o.threshold}`] : []),
    ...(o.keep ? [`keep: ${q(o.keep)}`] : []),
  ];

  return `// Generated by openclaw-jev-trigger. Edit freely.
// Condition (plain language), judged by the agent's decisionModel via jev_when.
const WHEN = ${q(o.when.trim())};
${o.notWhen?.trim() ? `const NOT_WHEN = ${q(o.notWhen.trim())};\n` : ""}const s = trigger.state ?? {};
const asText = (v) =>
  typeof v === "string" ? v
  : v && typeof v.aggregated === "string" ? v.aggregated
  : v && typeof v.text === "string" ? v.text
  : v && typeof v.content === "string" ? v.content
  : JSON.stringify(v);

const obs = asText(${observe}).trim();
const v = await jev_when({ ${askLines.join(", ")} });

if (v.unavailable) {
  // Not a "no": the judge could not answer. Stay quiet, but do not go silent forever.
  const misses = (s.misses ?? 0) + 1;
  json({
    fire: ${alertAfter > 0 ? `misses === ${alertAfter}` : "false"},
    message: \`jev-trigger: the judge was unavailable \${misses} times in a row (\${v.unavailable}). "\${WHEN}" is not being checked.\`,
    state: { ...s, misses },
  });
} else {
  const fire = v.matched${o.level ? "" : " && !s.matched"};
  json({
    fire,
    message: \`Condition met: \${WHEN}\\n(p=\${v.probability} ≥ \${v.threshold}, \${v.model})\\n\\nObservation:\\n\${obs.slice(-1500)}\`,
    state: { ${o.compare ? `last: obs.slice(-${stateChars}), ` : ""}matched: v.matched, p: v.probability, misses: 0 },
  });
}
`;
}
